# Generated by Django 4.2.1 on 2023-07-03 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0002_payment_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_item',
            name='email',
            field=models.EmailField(max_length=255, null=True),
        ),
    ]
