# Generated by Django 4.2.1 on 2023-07-06 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0003_payment_item_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_item',
            name='balance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment_item',
            name='current_balance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
