# Generated by Django 4.2.1 on 2023-07-07 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0004_payment_item_balance_payment_item_current_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_item',
            name='date',
            field=models.DateTimeField(blank=True, max_length=255, null=True),
        ),
    ]
