# Generated by Django 4.2.1 on 2023-07-07 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0005_alter_payment_item_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_item',
            name='date',
            field=models.DateField(blank=True, max_length=255, null=True),
        ),
    ]
