# Generated by Django 4.2.1 on 2023-07-08 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0007_payment_item_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment_item',
            name='user',
        ),
    ]
