# Generated by Django 4.2.1 on 2023-09-11 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0008_alter_payment_made_cash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banking',
            name='opening_bal',
            field=models.CharField(blank=True, default='', max_length=220, null=True),
        ),
    ]
