# Generated by Django 4.2.1 on 2023-09-12 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0009_alter_banking_opening_bal'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_made',
            name='gst_number',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
